name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ShellCheck sashi
        run: shellcheck -x sashi || true
      - name: ShellCheck scripts
        run: find scripts -name '*.sh' | xargs shellcheck || true
      - name: ShellCheck lib/sh
        run: find lib/sh -name '*.sh' | xargs shellcheck || true
      - name: Bash syntax check
        run: |
          for f in sashi scripts/*.sh lib/sh/*; do
            [ -f "$f" ] && bash -n "$f" && echo "OK: $f"
          done
