# Workflow: verify-run
# Prefix: verify | Suffix: run
# Audit: Runs verification test cases against live system
name: verify-run

on:
  workflow_dispatch:
    inputs:
      test_id:
        description: 'Specific VER-XX to run (or "all")'
        required: false
        default: 'all'

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List verification cases
        run: |
          echo "=== Verification Test Cases ==="
          for ver in kanban/tests/VER-*.md; do
            [ -f "$ver" ] || continue
            ID=$(basename "$ver" .md)
            TITLE=$(head -1 "$ver" | sed 's/^# //')
            BLOCKS=$(grep -oP 'Blocks:\s*\K.*' "$ver" || echo "?")
            echo "$ID | $TITLE | blocks: $BLOCKS"
          done

      - name: Log audit trail
        run: |
          echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) verify-run ${{ github.event.inputs.test_id }}" >> kanban/exports/audit.log
